const adventureActivities = [
  'Hiking',
  'Rock Climbing',
  'Mountain Biking',
  'Caving',
  'Canoeing',
  'Boating',
  'Kayaking',
  'Rafting',
  'Zip Lining',
  'Paragliding',
  'Skydiving',
  'Bungee Jumping',
  'Surfing',
  'Snowboarding',
  'Skiing',
  'Hang Gliding',
  'Scuba Diving',
  'Snorkeling',
  'Safari',
  'Sailing',
  'Canyoning',
  'Backpacking',
  'Off-Roading',
  'Base Jumping',
  'Cross-Country Running',
  'Parkour',
  'Survival Training',
  'Trekking',
  'Camping',
];

export default adventureActivities;
